CREATE TABLE INVOICE(
    INVOICE_ID VARCHAR(200) NOT NULL PRIMARY KEY,
    USER_ID VARCHAR(200) NOT NULL,
    INVOICE_NUMBER VARCHAR(200) NOT NULL,
    PRODUCT_IDS TEXT NOT NULL,
    CREATED_TIME TIMESTAMP NOT NULL,
    UPDATED_TIME TIMESTAMP NOT NULL
);